export const actionTypes = {
  GET_ALL_PROFILES: 'GET_ALL_PROFILES',
  SET_CLIENTS_PAGINATION: 'SET_CLIENTS_PAGINATION',
  SET_ALL_PROFILES: 'SET_ALL_PROFILES',
  GET_ALL_ADDRESSES_ACCOUNTS: 'GET_ALL_ADDRESSES_ACCOUNTS',
  SET_LIST_STATE: 'SET_LIST_STATE',
  SET_LIST_CITIES: 'SET_LIST_CITIES'
}
