export const actionTypes = {
  SET_ACCESS_TOKEN_FLOW: "SET_ACCESS_TOKEN_FLOW",
  SET_BODY_DATA_RECOVER: "SET_BODY_DATA_RECOVER",
  SET_AUTH_DATA: "SET_AUTH_DATA",
  SET_PROFILE_DATA: "SET_PROFILE_DATA",
  SET_USER_AUTH: "SET_USER_AUTH"
};
